apiVersion: v1
kind: Pod
metadata:
  name: abs-migrate
  namespace: audiobookshelf
spec:
  restartPolicy: Never
  nodeSelector:
    kubernetes.io/hostname: hl1
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
  containers:
    - name: rsync
      image: alpine
      command: ["sh","-c"]
      args:
        - |
          set -e
          apk add --no-cache rsync;
          # Ensure target subdirs exist (defensive)
          mkdir -p /new/config /new/metadata /new/audiobooks /new/books /new/podcasts;
          # Copy everything, preserving perms/links/xattrs
          rsync -aHAXv /old/ /new/;
          # Normalize ownership to match your pod securityContext (1000:1000)
          chown -R 1000:1000 /new;
          echo "DONE"; sleep 5
      volumeMounts:
        - { name: old, mountPath: /old }
        - { name: new, mountPath: /new }
  volumes:
    - name: old
      persistentVolumeClaim:
        claimName: audiobookshelf-data-pvc          # OLD claim
    - name: new
      persistentVolumeClaim:
        claimName: audiobookshelf-data-longhorn     # NEW claim

