apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-lubelogger
  namespace: lubelogger
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:15
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: pg-lubelogger
  storage:
    size: 1Gi
