apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-lubelogger-nodes
  namespace: lubelogger
spec:
  instances: 3

  # Keep the new DB off the control plane (hl1)
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/worker
            operator: Exists

  imageName: ghcr.io/cloudnative-pg/postgresql:15
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: pg-lubelogger
  
        # Spread replicas across workers if possible
  topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: ScheduleAnyway
    labelSelector:
      matchLabels:
        cnpg.io/cluster: pg-lubelogger-nodes

  storage:
    size: 5Gi
    storageClass:  longhorn-gp # e.g., longhorn, nfs-client, etc.

  # Restore from your existing Barman S3 backups
  bootstrap:
    recovery:
      source: s3-backups
      # Optional Point-In-Time recovery example:
      # recoveryTarget:
      #   targetTime: "2025-09-28 15:30:00+00"

  # Tell CNPG where the backups live
  externalClusters:
  - name: s3-backups
    barmanObjectStore:
      destinationPath: "s3://pg-lubelogger/lubelogger"
      s3Credentials:
        accessKeyId:
          name: aws-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: aws-creds
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
