apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lh-smoke
  namespace: lubelogger
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn-single
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: lh-smoke
  namespace: lubelogger
spec:
  containers:
  - name: c
    image: busybox
    command: ["sh","-c","sleep 3600"]
    volumeMounts:
    - name: v
      mountPath: /data
  volumes:
  - name: v
    persistentVolumeClaim:
      claimName: lh-smoke

