apiVersion: batch/v1
kind: CronJob
metadata:
  name: linkding-s3-backup
spec:
  schedule: "0 1 * * 0" #Sunday at 1:00 a.m.
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            kubernetes.io/hostname: hl2
          securityContext:
            fsGroup: 33
            runAsUser: 33
            runAsGroup: 33
          initContainers:
            - name: make-archive
              image: alpine:3.23
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - |
                  set -euo pipefail
                  TS="$(date -u +%Y-%m-%dT%H-%M-%SZ)"
                  ARCHIVE="/work/linkding-data-${TS}.tar.gz"
                  echo "$ARCHIVE" > /work/archive_path
                  tar czf "$ARCHIVE" -C /etc/linkding/data .

              volumeMounts:
                - name: linkding-data
                  mountPath: /etc/linkding/data
                - name: work
                  mountPath: /work
          containers:
            - name: linkding-backup
              image: amazon/aws-cli:2.17.57
              imagePullPolicy: IfNotPresent
              envFrom:
                - secretRef:
                    name: linkding-s3-backup
              env:
                - name: S3_BUCKET
                  value: "linkding-data-backup"
              command:
                - /bin/sh
                - -c
                - |
                  set -euo pipefail
                  ARCHIVE="$(cat /work/archive_path)"
                  aws s3 cp "$ARCHIVE" "s3://${S3_BUCKET}/linkding/$(basename "$ARCHIVE")"
              volumeMounts:
                - name: work
                  mountPath: /work
          restartPolicy: OnFailure

          volumes:
            - name: linkding-data
              persistentVolumeClaim:
                claimName: linkding-data-longhorn-v2
            - name: work
              emptyDir: {}
