apiVersion: apps/v1
kind: Deployment
metadata:
  name: lubelogger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lubelogger
  template:
    metadata:
      labels:
        app: lubelogger
    spec:
      # securityContext:
        #fsGroup: 33 # node group ID
        #runAsUser: 33 # node user ID
        #runAsGroup:  # node group ID

      containers:
        - name: lubelogger
          image: ghcr.io/hargata/lubelogger:v1.4.9
          ports:
            - containerPort: 8080

          #envFrom:
            #- configMapRef:
            #    name: audiobookshelf-config
            #- secretRef:
            #    name: linkding-container-env

          securityContext:
            allowPrivilegeEscalation: false
