apiVersion: apps/v1
kind: Deployment
metadata:
  name: lubelogger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lubelogger
  template:
    metadata:
      labels:
        app: lubelogger
    spec:
      #securityContext:
      #  runAsUser: 1000
      #  runAsGroup: 1000
      #  runAsNonRoot: true
      #  fsGroup: 1000
      
      containers:
        - name: lubelogger
          image: ghcr.io/hargata/lubelogger:v1.4.9
          ports:
            - containerPort: 8080
          
          env:
            - name: POSTGRES_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: pg-lubelogger-db-secret-nodes
                  key: POSTGRES_CONNECTION
          volumeMounts:
            - mountPath: "/App/data"
              name: app-data
          #envFrom:
            #- configMapRef:
            #    name: audiobookshelf-config
            #- secretRef:
            #    name: linkding-container-env

          securityContext:
            allowPrivilegeEscalation: false
      volumes:
        - name: app-data
          persistentVolumeClaim:
            claimName: lubelogger-fe-longhorn
