apiVersion: v1
kind: Service
metadata:
  name: lubelogger
  namespace: lubelogger
spec:
  ports:
    - port: 8081 #external port what cloudflared will call
      targetPort: 8080 #internal pod port
  selector:
    app: lubelogger
  type: ClusterIP
