apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 1m
  path: ./infrastructure/controllers/base/cert-manager
  prune: true
  wait: true
  timeout: 5m
  # targetNamespace is optional since the base already sets namespace: cert-manager
  targetNamespace: cert-manager
