apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "75.6.1"
      # version: "58.x"
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack
        namespace: monitoring
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
    ignore:
      # Ignore "validated" annotation which is not inserted during install
      - paths: ["/metadata/annotations/prometheus-operator-validated"]
        target:
          kind: PrometheusRule
  values:
    grafana:
      adminPassword: stihl460
      ingress:
        enabled: true

        ingressClassName: "traefik"

        ## Hostnames.
        ## Must be provided if Ingress is enabled.
        ##
        hosts:
          - grs.lucasbee066.org

        ## TLS configuration for Prometheus Ingress
        ## Secret must be manually created in the namespace
        ##
        tls:
        - secretName: grafana-tls-secret
           hosts:
             - grs.lucasbee066.org
