---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: vault
  namespace: linkding
spec:
  address: https://vault.vault-lucasbee066.name
  skipTLSVerify: false

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: linkding
  namespace: linkding
spec:
  vaultConnectionRef: vault
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: linkding
    serviceAccount: linkding

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: linkding-s3-backup
  namespace: linkding
spec:
  vaultAuthRef: linkding
  type: kv-v2
  mount: kv2
  path: homelab/linkding/s3-backup
  refreshAfter: 1h
  destination:
    name: linkding-s3-backup
    create: true
    overwrite: true
